name: 'Device Cloud Action'
author: 'devicecloud.dev'
description: 'Uses devicecloud.dev to execute Maestro mobile tests'
inputs:
  api-key:
    description: 'API key for devicecloud.dev (find this in the console UI). You can also set the DEVICE_CLOUD_API_KEY environment variable.'
    required: true
  api-url:
    description: 'API URL for devicecloud.dev'
    required: false
  app-file:
    description: 'App binary to run your flows against'
    required: false
  app-binary-id:
    description: 'The ID of the app binary previously uploaded to devicecloud.dev'
    required: false
  additional-app-files:
    description: 'Additional app binary(s) to install before executio ($0.10 cost per upload)'
    required: false
  additional-app-binary-ids:
    description: 'The ID of the additional app binary(s) previously uploaded to devicecloud.dev to install before execution'
    required: false
  android-api-level:
    description: '[Android only] Android API level to run your flow against <options: 29|30|31|32|33|34|35>'
    required: false
  android-device:
    description: '[Android only] Android device to run your flow against <options: pixel-6|pixel-6-pro|pixel-7|pixel-7-pro|generic-tablet>'
    required: false
  async:
    description: 'Immediately return (exit code 0) from the command without waiting for the results of the run (useful for saving CI minutes)'
    required: false
  device-locale:
    description: 'Locale that will be set to a device, ISO-639-1 code and uppercase ISO-3166-1 code e.g. "de_DE" for Germany'
    required: false
  download-artifacts:
    description: 'Download a zip containing the logs, screenshots and videos for each result in this run. You will debited a $0.01 egress fee for each result. Use FAILED for failures only or ALL for every result. <options: ALL|FAILED>'
    required: false
  env:
    description: 'One or more environment variables to inject into your flows'
    required: false
  json-file:
    description: 'Write JSON output to a file with name <run_name>_dcd.json or <upload_id>_dcd.json if no name is provided'
    required: false
  exclude-flows:
    description: 'Sub directories to ignore when building the flow file list'
    required: false
  exclude-tags:
    description: 'Flows which have these tags will be excluded from the run'
    required: false
  flows:
    description: 'The path to the flow file or folder containing your flows'
    required: false
  google-play:
    description: '[Android only] Run your flow against Google Play devices'
    required: false
  ignore-sha-check:
    description: 'Ignore the sha hash check and upload the binary regardless of whether it already exists (not recommended)'
    required: false
  include-tags:
    description: 'Only flows which have these tags will be included in the run'
    required: false
  ios-device:
    description: '[iOS only] iOS device to run your flow against <options: iphone-13|iphone-14|iphone-14-plus|iphone-14-pro|iphone-14-pro-max|iphone-15|iphone-15-plus|iphone-15-pro|iphone-15-pro-max|iphone-16|iphone-16-plus|iphone-16-pro|iphone-16-pro-max|ipad-pro-6th-gen>'
    required: false
  ios-version:
    description: '[iOS only] iOS version to run your flow against <options: 16|17|18>'
    required: false
  maestro-version:
    description: 'Maestro version to run your flow against'
    required: false
  moropo-v1-api-key:
    description: 'API key for Moropo v1 integration'
    required: false
  name:
    description: 'A custom name for your upload (useful for tagging commits etc)'
    required: false
  orientation:
    description: '[Android only] The orientation of the device to run your flow against in degrees <options: 0|90|180|270>'
    required: false
  quiet:
    description: 'Quieter console output that wont provide progress updates'
    required: false
  report:
    description: 'Runs Maestro with the --format flag, this will generate a report in the specified format <options: junit|html>'
    required: false
  retry:
    description: 'Number of times to retry the run if it fails (same as pressing retry in the UI, this is free)'
    required: false
  workspace:
    description: 'The path to the workspace folder containing your flows'
    required: false
    default: './.maestro/'
  config:
    description: 'Specific path to your maestro config file'
    required: false
  runner-type:
    description: '[experimental] The type of runner to use <options: m1|m4> - note: anything other than default will incur premium pricing tiers. See https://docs.devicecloud.dev/reference/runner-type for more information'
    required: false
    default: 'default'
  debug:
    description: 'Enable debug mode for more verbose output'
    required: false

outputs:
  DEVICE_CLOUD_CONSOLE_URL:
    description: 'URL to view the test results in the Device Cloud console'
  DEVICE_CLOUD_FLOW_RESULTS:
    description: 'JSON array containing results for each flow, including name, status, and any errors'
  DEVICE_CLOUD_UPLOAD_STATUS:
    description: 'Status of the test run (PENDING, RUNNING, PASSED, FAILED, CANCELLED)'
  DEVICE_CLOUD_APP_BINARY_ID:
    description: 'ID of the uploaded app binary in Device Cloud'

runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'check'
  color: 'blue'
